# Generated by Django 5.1.2 on 2024-11-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SignLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_firstname', models.CharField(max_length=50, verbose_name="Tutor's First Name")),
                ('tutor_lastname', models.CharField(max_length=50, verbose_name="Tutor's Surname")),
                ('tutor_email', models.EmailField(max_length=254, unique=True, verbose_name="Tutor's Email Address")),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('photo', models.ImageField(default='tutor_images/default.jpg', upload_to='tutor_images/')),
                ('day_availability', models.ManyToManyField(to='tutor.dayavailability')),
                ('programming_languages', models.ManyToManyField(to='tutor.programminglanguage')),
                ('sign_languages', models.ManyToManyField(to='tutor.signlanguage')),
                ('time_availability', models.ManyToManyField(to='tutor.timeslot')),
            ],
        ),
    ]
