# Generated by Django 5.1.2 on 2024-11-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_alter_dayavailability_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayavailability',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='dayavailability',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
