# Generated by Django 5.1.2 on 2024-11-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_alter_dayavailability_options_dayavailability_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayavailability',
            options={'ordering': ['order'], 'verbose_name': 'Day Availability', 'verbose_name_plural': 'Day Availabilities'},
        ),
        migrations.AlterField(
            model_name='tutor',
            name='programming_languages',
            field=models.ManyToManyField(related_name='tutors', to='tutor.programminglanguage'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='sign_languages',
            field=models.ManyToManyField(related_name='tutors', to='tutor.signlanguage'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='time_availability',
            field=models.ManyToManyField(related_name='tutors', to='tutor.timeslot'),
        ),
    ]
