# Generated by Django 5.1.2 on 2024-11-10 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_dayavailability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name="Tutor's Email Address"),
        ),
    ]
