# Generated by Django 5.1.2 on 2024-11-22 18:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_alter_tutor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/do2wq4dsx/image/upload/v1732298656/default_tutor_fsqznn.jpg', max_length=255, verbose_name='profile_picture'),
        ),
    ]
