# Generated by Django 5.1.2 on 2024-11-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Booking Date'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(editable=False, max_length=32, unique=True, verbose_name='Booking ID'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='stripe_pid',
            field=models.CharField(default='', editable=False, max_length=254, verbose_name='Stripe Payment ID'),
        ),
    ]
