# Generated by Django 5.1.2 on 2024-11-17 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_booking_date_alter_booking_booking_id_and_more'),
        ('tutor', '0005_alter_tutor_price_alter_tutor_tutor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.dayavailability')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.timeslot')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='tutor.tutor')),
            ],
            options={
                'unique_together': {('tutor', 'day_availability', 'time_slot')},
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking.tutoravailability'),
        ),
    ]
