# Generated by Django 5.1.2 on 2024-11-18 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_time_slot_booking_session_time_and_more'),
        ('tutor', '0005_alter_tutor_price_alter_tutor_tutor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='session_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='session_time',
            field=models.ManyToManyField(related_name='bookings', to='tutor.timeslot'),
        ),
    ]
