# Generated by Django 5.1.2 on 2024-11-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_payment_status'),
        ('personaluser', '0002_alter_profile_personal_details_and_more'),
        ('tutor', '0008_alter_tutor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tutor_email',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='tutor_fullname',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_email',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user_fullname',
            field=models.CharField(max_length=101, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tutor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tutor.tutor'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='personaluser.profile'),
        ),
    ]
