# Generated by Django 5.1.2 on 2024-11-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_booking_total_price_alter_booking_tutor_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tutor_email',
            field=models.CharField(max_length=254, null=True, verbose_name="Tutor's Email address"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tutor_fullname',
            field=models.CharField(max_length=101, null=True, verbose_name="Tutor's Full Name"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_email',
            field=models.CharField(max_length=254, null=True, verbose_name="User's Email address"),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_fullname',
            field=models.CharField(max_length=101, null=True, verbose_name="User's Full Name"),
        ),
    ]
